#!/usr/bin/env node
// Reads all skills SKILL.md files, parses YAML frontmatter,
// and writes src/skills-data.js so the site auto-discovers skills.
// Run: node scripts/generate-skills.js

import { writeFileSync } from "fs";
import { join } from "path";
import { ROOT, readAllSkills, getLastUpdated } from "./lib/parse-skill.js";

const OUTPUT = join(ROOT, "src", "skills-data.js");

const allSkills = readAllSkills();
const errors = [];

// Validate required fields
for (const skill of allSkills) {
  const missing = ["id", "name", "category"].filter((f) => !skill.meta[f]);
  if (missing.length) {
    errors.push(
      `${skill.dir}/SKILL.md: missing required fields: ${missing.join(", ")}`
    );
  }
}

if (errors.length) {
  console.error("ERRORS in skill files:");
  errors.forEach((e) => console.error(`  - ${e}`));
  process.exit(1);
}

// Validate dependency graph: every dependency must reference an existing skill ID
const allIds = new Set(allSkills.map((s) => s.meta.id));
for (const skill of allSkills) {
  const deps = Array.isArray(skill.meta.dependencies)
    ? skill.meta.dependencies
    : [];
  for (const dep of deps) {
    if (!allIds.has(dep)) {
      errors.push(
        `${skill.dir}/SKILL.md: dependency "${dep}" does not match any skill ID`
      );
    }
  }
}

if (errors.length) {
  console.error("ERRORS in skill dependencies:");
  errors.forEach((e) => console.error(`  - ${e}`));
  process.exit(1);
}

const skills = allSkills.map((s) => ({
  id: s.meta.id,
  name: s.meta.name,
  category: s.meta.category,
  description: s.meta.description || "",
  endpoints: s.meta.endpoints || 0,
  lastUpdated: getLastUpdated(s.filePath),
  version: s.meta.version || "1.0.0",
  status: s.meta.status || "stable",
  dependencies: Array.isArray(s.meta.dependencies) ? s.meta.dependencies : [],
  content: s.body,
}));

// Sort alphabetically by name for consistent output
skills.sort((a, b) => a.name.localeCompare(b.name));

const output = `// Auto-generated by scripts/generate-skills.js — do not edit manually
// To update: edit the YAML frontmatter in skills/*/SKILL.md and rebuild
export const SKILLS = ${JSON.stringify(skills, null, 2)};
`;

writeFileSync(OUTPUT, output);
console.log(`Generated ${skills.length} skills -> src/skills-data.js`);
