name: PR

on:
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  checks:
    uses: ./.github/workflows/_checks.yml
    permissions:
      contents: read
      pull-requests: write
